apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8s-sd-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-sd-agent.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
{{- if .Values.discovery.healthCheck }}
- apiGroups:
  - "discovery.k8s.io"
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
{{- end }}
