apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8s-sd-controller.fullname . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-sd-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch